// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-wqZbruQauiz1mYDTj4I77K4NsmeFS8',
    appId: '1:250644030711:web:066e8944885b84a6931ff2',
    messagingSenderId: '250644030711',
    projectId: 'loginsignupscreens',
    authDomain: 'loginsignupscreens.firebaseapp.com',
    storageBucket: 'loginsignupscreens.firebasestorage.app',
    measurementId: 'G-MWXXTCC1BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72WD3HcQYtzFRdHBPprhLlHfeDJuxivA',
    appId: '1:250644030711:android:b73dfc315960e8af931ff2',
    messagingSenderId: '250644030711',
    projectId: 'loginsignupscreens',
    storageBucket: 'loginsignupscreens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXw-aGa9EI5wtXnVaJNEmwyRRSX73svVA',
    appId: '1:250644030711:ios:c6029aff53524ca5931ff2',
    messagingSenderId: '250644030711',
    projectId: 'loginsignupscreens',
    storageBucket: 'loginsignupscreens.firebasestorage.app',
    iosBundleId: 'com.thiagogarcia.loginSignupScreens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXw-aGa9EI5wtXnVaJNEmwyRRSX73svVA',
    appId: '1:250644030711:ios:c6029aff53524ca5931ff2',
    messagingSenderId: '250644030711',
    projectId: 'loginsignupscreens',
    storageBucket: 'loginsignupscreens.firebasestorage.app',
    iosBundleId: 'com.thiagogarcia.loginSignupScreens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ-wqZbruQauiz1mYDTj4I77K4NsmeFS8',
    appId: '1:250644030711:web:de5d3a1647bffa05931ff2',
    messagingSenderId: '250644030711',
    projectId: 'loginsignupscreens',
    authDomain: 'loginsignupscreens.firebaseapp.com',
    storageBucket: 'loginsignupscreens.firebasestorage.app',
    measurementId: 'G-5B35MS62BV',
  );
}
